### ISSUE TITLE
[Decision] Tech stack

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/v3#1]
The comparison rubric: https://docs.google.com/document/d/1kCDWHyGhvu4Gdh0Ctzjlu3kVpvrljz-y7Uc-yF_uWJI/edit

![image](https://user-images.githubusercontent.com/4512699/66886240-9329e600-ef8b-11e9-8263-e25eb4d1059d.png)

**Comment by lpatmo** [comment]
What I'm leaning towards right now:

**Front-end**
React hosted on Netlify with GraphQL

**Back-end**
Django Rest Framework with a Postgres DB hosted on AWS
Lambda functions on Netlify with FaunaDB 

Django advantages: 
- users and user roles come out of the box

Netlify advantages:
- one repo, and no need to host the backend separately on a different server

Feel grateful to @cbelsole and @angelocordon, and @peoray for looking into React, Node, and Vue, but feel like Django or Netlify would draw more contributors. Still happy to be convinced the other way, though.

**Next Steps**
1. Estimate how expensive Netlify w/ lambda functions can get and compare with estimated costs hosting Django on AWS (help wanted)
2. Try to get a gauge of whether new contributors (who haven't touched the prototypes yet) would find it easier writing netlify-lambda functions or adding to Django DRF

**Comment by angelocordon** [comment]
Does it sound like we'll be moving forward with Django DRF + React front end?

**Comment by lpatmo** [comment]
Whoops, didn't follow up here... decision to move ahead with Django DRF + React documented here: https://github.com/codebuddies/backend/wiki/Decision-log#december-9th-2019

Closing this issue now. :)
